ansi2{htmltags,markdown}: Robustness: Do not accept unknown -* options

diff --git a/bin/ansi2htmltags b/bin/ansi2htmltags
--- a/bin/ansi2htmltags
+++ b/bin/ansi2htmltags
@@ -4,7 +4,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-l|--linkify [whole|noprotocol|noquery|host|path|leaf]] [-t|--tag TAG] FILE [...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-l|--linkify [whole|noprotocol|noquery|host|path|leaf]] [-t|--tag TAG] [--] FILE [...] [-?|-h|--help]'
     printf 'Usage: cat FILE [...] [| escapeHtml] | %q %s\n' "$(basename "$1")" '[...]'
 }
 printUsage()
@@ -70,6 +70,7 @@ do
 		    shift
 		    ;;
 	--)	    shift; break;;
+	-*)	    { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)	    break;;
     esac
 done
diff --git a/bin/ansi2markdown b/bin/ansi2markdown
--- a/bin/ansi2markdown
+++ b/bin/ansi2markdown
@@ -6,7 +6,7 @@ printUsage()
 Convert (some basic) ANSI escape sequences to Markdown format with http:// URLs
 turned into a link.
 HELPTEXT
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-l|--linkify [whole|noprotocol|noquery|host|path|leaf]] FILE [...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-l|--linkify [whole|noprotocol|noquery|host|path|leaf]] [--] FILE [...] [-?|-h|--help]'
     printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '[...]'
 }
 
@@ -29,6 +29,7 @@ do
 		    esac
 		    ;;
 	--)	    shift; break;;
+	-*)	    { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)	    break;;
     esac
 done
